# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CBSSports-Getopt
version:      1.1
version_from: lib/CBSSports/Getopt.pm
installdirs:  site
requires:
    File::Basename:                0
    File::HomeDir:                 0
    FindBin:                       0
    Getopt::Long:                  0
    Pod::Usage:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.25
